name: glassy_notes_app
description: A Flutter app with macOS style glassmorphism
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core:
  firebase_auth:
  cloud_firestore:
  # State Management
  get:

  # Navigation
  go_router:

  # UI Components
  google_fonts:
  flutter_staggered_animations:
  shimmer:

  # Utilities
  intl:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons:
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 23
  adaptive_icon_background: "#DCEEFF"
  adaptive_icon_foreground: "assets/images/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/